version: "3"

services:

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379

  python_app:
     build: 
        context: .
        dockerfile: Dockerfile
     depends_on:
       - redis
     ports:
       - 8000:8000

